name: dsc_wait_prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0
  - alembic=1.13.1
  - aom=3.8.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - cairo=1.18.0
  - catboost=1.2.3
  - certifi=2024.2.2
  - click=8.1.7
  - colorama=0.4.6
  - colorlog=6.8.2
  - contourpy=1.2.1
  - cuda-version=12.4
  - cycler=0.12.1
  - dav1d=1.2.1
  - double-conversion=3.3.0
  - expat=2.6.2
  - ffmpeg=6.1.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.51.0
  - freeglut=3.2.2
  - freetype=2.12.1
  - fribidi=1.0.10
  - getopt-win32=0.1
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - glib=2.80.0
  - glib-tools=2.80.0
  - graphite2=1.3.13
  - graphviz=9.0.0
  - greenlet=3.0.3
  - gst-plugins-base=1.24.1
  - gstreamer=1.24.1
  - gts=0.7.6
  - harfbuzz=8.3.0
  - hdf5=1.14.3
  - icu=73.2
  - imath=3.1.11
  - importlib-metadata=7.1.0
  - importlib_resources=6.4.0
  - intel-openmp=2024.1.0
  - jasper=4.2.3
  - joblib=1.4.0
  - khronos-opencl-icd-loader=2023.04.17
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240116.1
  - libaec=1.1.3
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang13=18.1.3
  - libcurl=8.7.1
  - libdeflate=1.20
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgd=2.3.3
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libglib=2.80.0
  - libhwloc=2.9.3
  - libiconv=1.17
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libogg=1.3.4
  - libopencv=4.9.0
  - libopenvino=2024.0.0
  - libopenvino-auto-batch-plugin=2024.0.0
  - libopenvino-auto-plugin=2024.0.0
  - libopenvino-hetero-plugin=2024.0.0
  - libopenvino-intel-cpu-plugin=2024.0.0
  - libopenvino-intel-gpu-plugin=2024.0.0
  - libopenvino-ir-frontend=2024.0.0
  - libopenvino-onnx-frontend=2024.0.0
  - libopenvino-paddle-frontend=2024.0.0
  - libopenvino-pytorch-frontend=2024.0.0
  - libopenvino-tensorflow-frontend=2024.0.0
  - libopenvino-tensorflow-lite-frontend=2024.0.0
  - libopus=1.3.1
  - libpng=1.6.43
  - libprotobuf=4.25.3
  - libsqlite=3.45.2
  - libssh2=1.11.0
  - libtiff=4.6.0
  - libvorbis=1.3.7
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxgboost=2.0.3
  - libxml2=2.12.6
  - libzlib=1.2.13
  - lightgbm=4.3.0
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - mako=1.3.3
  - markupsafe=2.1.5
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - mkl=2024.1.0
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - numpy=1.26.4
  - opencv=4.9.0
  - openexr=3.2.2
  - openh264=2.4.1
  - openjpeg=2.5.2
  - openssl=3.2.1
  - optuna=3.6.0
  - packaging=24.0
  - pandas=2.2.2
  - pango=1.52.2
  - pcre2=10.43
  - pillow=10.3.0
  - pip=24.0
  - pixman=0.43.4
  - plotly=5.19.0
  - ply=3.11
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pugixml=1.14
  - py-opencv=4.9.0
  - py-xgboost=2.0.3
  - pyparsing=3.1.2
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - python=3.12.2
  - python-dateutil=2.9.0
  - python-dotenv=0.21.0
  - python-graphviz=0.20.3
  - python-tzdata=2024.1
  - python_abi=3.12
  - pytz=2024.1
  - pyyaml=6.0.1
  - qt-main=5.15.8
  - qt6-main=6.6.3
  - scikit-learn=1.4.2
  - scipy=1.13.0
  - setuptools=69.2.0
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.2.0
  - sqlalchemy=2.0.29
  - svt-av1=2.0.0
  - tbb=2021.11.0
  - tenacity=8.2.3
  - threadpoolctl=3.4.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.4
  - tqdm=4.66.2
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.38.33130
  - vs2015_runtime=14.38.33130
  - wheel=0.43.0
  - x264=1!164.3095
  - x265=3.5
  - xgboost=2.0.3
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxpm=3.5.17
  - xorg-libxt=1.3.0
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - arrow==1.3.0
      - binaryornot==0.4.4
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - cookiecutter==2.6.0
      - idna==3.7
      - jinja2==3.1.3
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - polars==0.20.19
      - pyarray==0.2
      - pygments==2.17.2
      - python-slugify==8.0.4
      - requests==2.31.0
      - rich==13.7.1
      - text-unidecode==1.3
      - types-python-dateutil==2.9.0.20240316
      - make==4.3
      - urllib3==2.2.1
      - pyarrow==15.0.2
      - GPUtil
      - e .
